
# This file is automatically generated, you probably don't want to edit this

simiscoremacOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simiscoremacOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sotext = NULL,
            tatext = NULL, ...) {

            super$initialize(
                package="SimiScoreMac",
                name="simiscoremac",
                requiresData=TRUE,
                ...)

            private$..sotext <- jmvcore::OptionVariable$new(
                "sotext",
                sotext)
            private$..tatext <- jmvcore::OptionVariables$new(
                "tatext",
                tatext)

            self$.addOption(private$..sotext)
            self$.addOption(private$..tatext)
        }),
    active = list(
        sotext = function() private$..sotext$value,
        tatext = function() private$..tatext$value),
    private = list(
        ..sotext = NA,
        ..tatext = NA)
)

simiscoremacResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simiscoremacResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Text Simialrity Scoring Mac")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Text Simialrity Scoring Mac"))}))

simiscoremacBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simiscoremacBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SimiScoreMac",
                name = "simiscoremac",
                version = c(1,0,0),
                options = options,
                results = simiscoremacResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Text Simialrity Scoring Mac
#'
#' 
#' @param data .
#' @param sotext .
#' @param tatext .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
simiscoremac <- function(
    data,
    sotext,
    tatext) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simiscoremac requires jmvcore to be installed (restart may be required)")

    if ( ! missing(sotext)) sotext <- jmvcore::resolveQuo(jmvcore::enquo(sotext))
    if ( ! missing(tatext)) tatext <- jmvcore::resolveQuo(jmvcore::enquo(tatext))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(sotext), sotext, NULL),
            `if`( ! missing(tatext), tatext, NULL))


    options <- simiscoremacOptions$new(
        sotext = sotext,
        tatext = tatext)

    analysis <- simiscoremacClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

